//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.26 at 10:41:23 PM CET 
//


package al.recipes.categories;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the al.recipes.categories package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
    
    private final static QName _GetCategoriesRequest_QNAME = new QName("categories.recipes.al", "getCategoriesRequest");
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: al.recipes.categories
     */
    public ObjectFactory() {
    }
    
    /**
     * Create an instance of {@link GetCategoriesResponse }
     */
    public GetCategoriesResponse createGetCategoriesResponse() {
        return new GetCategoriesResponse();
    }
    
    /**
     * Create an instance of {@link Categories }
     */
    public Categories createCategories() {
        return new Categories();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     */
    @XmlElementDecl(namespace = "categories.recipes.al", name = "getCategoriesRequest")
    public JAXBElement<Object> createGetCategoriesRequest(Object value) {
        return new JAXBElement<>(_GetCategoriesRequest_QNAME, Object.class, null, value);
    }
    
}
